const DB={get(k,d){try{let v=localStorage.getItem("alqaysar_"+k);return v?JSON.parse(v):d}catch(e){return d}},set(k,v){localStorage.setItem("alqaysar_"+k,JSON.stringify(v))}};
function doLogin(){let p=document.getElementById("adminPassword").value,s=DB.get("password","admin123");if(p===s){sessionStorage.setItem("alqaysar_admin","true");document.getElementById("loginScreen").style.display="none";document.getElementById("adminLayout").classList.add("active");initAdmin()}else{document.getElementById("loginError").style.display="block"}}
function logout(){sessionStorage.removeItem("alqaysar_admin");location.reload()}
function checkAuth(){if(sessionStorage.getItem("alqaysar_admin")==="true"){document.getElementById("loginScreen").style.display="none";document.getElementById("adminLayout").classList.add("active");initAdmin()}}
function toast(m,t){let c=document.getElementById("toastContainer"),d=document.createElement("div");d.className="toast "+(t||"success");let i=t==="error"?"fa-exclamation-circle":t==="info"?"fa-info-circle":"fa-check-circle";d.innerHTML='<i class="fas '+i+'"></i><span>'+m+"</span>";c.appendChild(d);setTimeout(()=>d.remove(),4000)}
function showSection(id,el){document.querySelectorAll(".section-content").forEach(s=>s.style.display="none");document.getElementById(id+"-section").style.display="block";document.querySelectorAll(".sidebar-menu a").forEach(a=>a.classList.remove("active"));if(el)el.classList.add("active");let T={dashboard:"لوحة التحكم",menu:"إدارة القائمة",categories:"التصنيفات",offers:"العروض",settings:"إعدادات الموقع",appearance:"تخصيص المظهر"};document.getElementById("page-title").innerHTML='<i class="fas '+(el?el.querySelector("i").className.replace("fas ",""):"fa-tachometer-alt")+'"></i> '+T[id];if(id==="menu")renderMenuTable();if(id==="categories")renderCategoriesTable();if(id==="offers")renderOffersTable();if(id==="settings")loadSettings();if(id==="appearance")loadAppearance();if(window.innerWidth<768)document.getElementById("sidebar").classList.remove("open")}
function toggleSidebar(){document.getElementById("sidebar").classList.toggle("open")}
function showTab(t,b){document.querySelectorAll(".tab-content").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tab-btn").forEach(x=>x.classList.remove("active"));document.getElementById("tab-"+t).classList.add("active");b.classList.add("active")}
function updateStats(){document.getElementById("stat-items").textContent=DB.get("menu",[]).length;document.getElementById("stat-cats").textContent=DB.get("categories",[]).length;document.getElementById("stat-offers").textContent=DB.get("offers",[]).filter(o=>o.active).length;document.getElementById("stat-visits").textContent=DB.get("visits",0)}
function renderMenuTable(){let items=DB.get("menu",[]),search=document.getElementById("menuSearch").value.toLowerCase(),filtered=items.filter(i=>i.name.toLowerCase().includes(search)),cats=DB.get("categories",[]),tbody=document.getElementById("menuTableBody");document.getElementById("menuEmpty").style.display=filtered.length?"none":"block";tbody.innerHTML=filtered.map((item,idx)=>{let cat=cats.find(c=>c.id==item.category);return"<tr><td>"+(idx+1)+"</td><td><div class=\"item-img\">"+(item.image?'<img src="'+item.image+'" style="width:48px;height:48px;object-fit:cover;border-radius:10px">':'<i class="fas fa-image"></i>')+"</div></td><td><strong>"+item.name+"</strong></td><td>"+(cat?cat.name:"--")+"</td><td>"+(item.price?item.price.toLocaleString("ar-SA"):"--")+"</td><td><span class=\"badge "+(item.active?"badge-success":"badge-danger")+"\">"+(item.active?"متاح":"غير متاح")+"</span></td><td><button class=\"btn btn-sm btn-secondary\" onclick=\"editItem("+item.id+")\"><i class=\"fas fa-edit\"></i></button> <button class=\"btn btn-sm btn-danger\" onclick=\"deleteItem("+item.id+")\"><i class=\"fas fa-trash\"></i></button></td></tr>"}).join("")}
function openItemModal(){document.getElementById("item-id").value="";document.getElementById("item-name").value="";document.getElementById("item-price").value="";document.getElementById("item-desc").value="";document.getElementById("item-image").value="";document.getElementById("item-preview").style.display="none";document.getElementById("item-active-toggle").classList.add("active");document.getElementById("itemModalTitle").innerHTML='<i class="fas fa-plus"></i> إضافة صنف جديد';populateCategorySelect();document.getElementById("itemModal").classList.add("active")}
function editItem(id){let item=DB.get("menu",[]).find(i=>i.id===id);if(!item)return;document.getElementById("item-id").value=item.id;document.getElementById("item-name").value=item.name;document.getElementById("item-price").value=item.price;document.getElementById("item-desc").value=item.desc||"";document.getElementById("item-image").value=item.image||"";previewImage(item.image,"item-preview");document.getElementById("item-active-toggle").classList.toggle("active",item.active);document.getElementById("itemModalTitle").innerHTML='<i class="fas fa-edit"></i> تعديل صنف';populateCategorySelect(item.category);document.getElementById("itemModal").classList.add("active")}
function saveItem(){let id=document.getElementById("item-id").value,name=document.getElementById("item-name").value.trim(),price=parseFloat(document.getElementById("item-price").value),category=document.getElementById("item-category").value;if(!name||!price||!category){toast("يرجى ملء جميع الحقول المطلوبة","error");return}let items=DB.get("menu",[]),data={id:id?parseInt(id):Date.now(),name,price,category:parseInt(category),desc:document.getElementById("item-desc").value.trim(),image:document.getElementById("item-image").value.trim(),active:document.getElementById("item-active-toggle").classList.contains("active")};if(id){let idx=items.findIndex(i=>i.id===parseInt(id));if(idx>-1)items[idx]=data}else items.push(data);DB.set("menu",items);closeItemModal();renderMenuTable();updateStats();toast("تم حفظ الصنف بنجاح")}
function deleteItem(id){if(!confirm("هل أنت متأكد من حذف هذا الصنف؟"))return;DB.set("menu",DB.get("menu",[]).filter(i=>i.id!==id));renderMenuTable();updateStats();toast("تم الحذف بنجاح")}
function closeItemModal(){document.getElementById("itemModal").classList.remove("active")}
function populateCategorySelect(sel){let cats=DB.get("categories",[]),s=document.getElementById("item-category");s.innerHTML='<option value="">اختر التصنيف</option>'+cats.map(c=>'<option value="'+c.id+'"'+(c.id==sel?' selected':"")+">"+c.name+"</option>").join("")}
function previewImage(url,id){let img=document.getElementById(id);if(url){img.src=url;img.style.display="block"}else img.style.display="none"}
function renderCategoriesTable(){let cats=DB.get("categories",[]),items=DB.get("menu",[]),tbody=document.getElementById("categoriesTableBody");tbody.innerHTML=cats.map((c,idx)=>{let count=items.filter(i=>i.category==c.id).length;return"<tr><td>"+(idx+1)+"</td><td><strong>"+c.name+"</strong></td><td><i class=\"fas "+(c.icon||"fa-tag")+"\"></i></td><td>"+count+"</td><td><button class=\"btn btn-sm btn-secondary\" onclick=\"editCategory("+c.id+")\"><i class=\"fas fa-edit\"></i></button> <button class=\"btn btn-sm btn-danger\" onclick=\"deleteCategory("+c.id+")\"><i class=\"fas fa-trash\"></i></button></td></tr>"}).join("")}
function openCategoryModal(){document.getElementById("cat-id").value="";document.getElementById("cat-name").value="";document.getElementById("cat-icon").value="";document.getElementById("catModalTitle").innerHTML='<i class="fas fa-plus"></i> إضافة تصنيف';document.getElementById("categoryModal").classList.add("active")}
function editCategory(id){let cat=DB.get("categories",[]).find(c=>c.id===id);if(!cat)return;document.getElementById("cat-id").value=cat.id;document.getElementById("cat-name").value=cat.name;document.getElementById("cat-icon").value=cat.icon||"";document.getElementById("catModalTitle").innerHTML='<i class="fas fa-edit"></i> تعديل تصنيف';document.getElementById("categoryModal").classList.add("active")}
function saveCategory(){let id=document.getElementById("cat-id").value,name=document.getElementById("cat-name").value.trim();if(!name){toast("يرجى إدخال اسم التصنيف","error");return}let cats=DB.get("categories",[]),data={id:id?parseInt(id):Date.now(),name,icon:document.getElementById("cat-icon").value.trim()||"fa-tag"};if(id){let idx=cats.findIndex(c=>c.id===parseInt(id));if(idx>-1)cats[idx]=data}else cats.push(data);DB.set("categories",cats);closeCategoryModal();renderCategoriesTable();updateStats();toast("تم حفظ التصنيف بنجاح")}
function deleteCategory(id){if(!confirm("هل أنت متأكد؟ سيتم حذف التصنيف فقط."))return;DB.set("categories",DB.get("categories",[]).filter(c=>c.id!==id));renderCategoriesTable();updateStats();toast("تم الحذف بنجاح")}
function closeCategoryModal(){document.getElementById("categoryModal").classList.remove("active")}
function renderOffersTable(){let offers=DB.get("offers",[]),tbody=document.getElementById("offersTableBody");document.getElementById("offersEmpty").style.display=offers.length?"none":"block";tbody.innerHTML=offers.map((o,idx)=>"<tr><td>"+(idx+1)+"</td><td><div class=\"item-img\">"+(o.image?'<img src="'+o.image+'" style="width:48px;height:48px;object-fit:cover;border-radius:10px">':'<i class="fas fa-image"></i>')+"</div></td><td><strong>"+o.title+"</strong></td><td>"+(o.desc||"--")+"</td><td>"+(o.price?o.price.toLocaleString("ar-SA"):"--")+"</td><td><span class=\"badge "+(o.active?"badge-success":"badge-danger")+"\">"+(o.active?"نشط":"معطل")+"</span></td><td><button class=\"btn btn-sm btn-secondary\" onclick=\"editOffer("+o.id+")\"><i class=\"fas fa-edit\"></i></button> <button class=\"btn btn-sm btn-danger\" onclick=\"deleteOffer("+o.id+")\"><i class=\"fas fa-trash\"></i></button></td></tr>").join("")}
function openOfferModal(){document.getElementById("offer-id").value="";document.getElementById("offer-title").value="";document.getElementById("offer-desc").value="";document.getElementById("offer-price").value="";document.getElementById("offer-oldprice").value="";document.getElementById("offer-image").value="";document.getElementById("offer-active-toggle").classList.add("active");document.getElementById("offerModalTitle").innerHTML='<i class="fas fa-plus"></i> إضافة عرض';document.getElementById("offerModal").classList.add("active")}
function editOffer(id){let o=DB.get("offers",[]).find(x=>x.id===id);if(!o)return;document.getElementById("offer-id").value=o.id;document.getElementById("offer-title").value=o.title;document.getElementById("offer-desc").value=o.desc||"";document.getElementById("offer-price").value=o.price;document.getElementById("offer-oldprice").value=o.oldPrice||"";document.getElementById("offer-image").value=o.image||"";document.getElementById("offer-active-toggle").classList.toggle("active",o.active);document.getElementById("offerModalTitle").innerHTML='<i class="fas fa-edit"></i> تعديل عرض';document.getElementById("offerModal").classList.add("active")}
function saveOffer(){let id=document.getElementById("offer-id").value,title=document.getElementById("offer-title").value.trim(),price=parseFloat(document.getElementById("offer-price").value);if(!title||!price){toast("يرجى ملء الحقول المطلوبة","error");return}let offers=DB.get("offers",[]),data={id:id?parseInt(id):Date.now(),title,price,desc:document.getElementById("offer-desc").value.trim(),oldPrice:parseFloat(document.getElementById("offer-oldprice").value)||0,image:document.getElementById("offer-image").value.trim(),active:document.getElementById("offer-active-toggle").classList.contains("active")};if(id){let idx=offers.findIndex(o=>o.id===parseInt(id));if(idx>-1)offers[idx]=data}else offers.push(data);DB.set("offers",offers);closeOfferModal();renderOffersTable();updateStats();toast("تم حفظ العرض بنجاح")}
function deleteOffer(id){if(!confirm("هل أنت متأكد من حذف هذا العرض؟"))return;DB.set("offers",DB.get("offers",[]).filter(o=>o.id!==id));renderOffersTable();updateStats();toast("تم الحذف بنجاح")}
function closeOfferModal(){document.getElementById("offerModal").classList.remove("active")}
function loadSettings(){let s=DB.get("settings",{});document.getElementById("site-name").value=s.name||"";document.getElementById("site-subtitle").value=s.subtitle||"";document.getElementById("site-desc").value=s.desc||"";document.getElementById("site-address").value=s.address||"";document.getElementById("site-hours").value=s.hours||"";document.getElementById("site-email").value=s.email||"";document.getElementById("site-phone").value=s.phone||"";document.getElementById("site-whatsapp").value=s.whatsapp||"";document.getElementById("site-phone2").value=s.phone2||"";document.getElementById("social-facebook").value=s.facebook||"";document.getElementById("social-instagram").value=s.instagram||"";document.getElementById("social-twitter").value=s.twitter||"";document.getElementById("social-tiktok").value=s.tiktok||"";document.getElementById("social-snapchat").value=s.snapchat||"";document.getElementById("social-youtube").value=s.youtube||""}
function saveSettings(){let s=DB.get("settings",{});s.name=document.getElementById("site-name").value.trim();s.subtitle=document.getElementById("site-subtitle").value.trim();s.desc=document.getElementById("site-desc").value.trim();s.address=document.getElementById("site-address").value.trim();s.hours=document.getElementById("site-hours").value.trim();s.email=document.getElementById("site-email").value.trim();s.phone=document.getElementById("site-phone").value.trim();s.whatsapp=document.getElementById("site-whatsapp").value.trim();s.phone2=document.getElementById("site-phone2").value.trim();s.facebook=document.getElementById("social-facebook").value.trim();s.instagram=document.getElementById("social-instagram").value.trim();s.twitter=document.getElementById("social-twitter").value.trim();s.tiktok=document.getElementById("social-tiktok").value.trim();s.snapchat=document.getElementById("social-snapchat").value.trim();s.youtube=document.getElementById("social-youtube").value.trim();let np=document.getElementById("new-password").value,cp=document.getElementById("confirm-password").value;if(np){if(np!==cp){toast("كلمتا المرور غير متطابقتين","error");return}DB.set("password",np);document.getElementById("new-password").value="";document.getElementById("confirm-password").value=""}DB.set("settings",s);toast("تم حفظ الإعدادات بنجاح")}
function loadAppearance(){let s=DB.get("settings",{});document.getElementById("logo-url").value=s.logoUrl||"";document.getElementById("hero-bg").value=s.heroBg||"";document.querySelectorAll("#primary-colors .color-option").forEach(el=>el.classList.toggle("active",el.dataset.color===(s.primaryColor||"#e67e22")));document.querySelectorAll("#dark-colors .color-option").forEach(el=>el.classList.toggle("active",el.dataset.color===(s.darkColor||"#1a1a2e")))}
function selectColor(el,type){document.querySelectorAll("#"+type+"-colors .color-option").forEach(c=>c.classList.remove("active"));el.classList.add("active")}
function saveAppearance(){let s=DB.get("settings",{}),pColor=document.querySelector("#primary-colors .color-option.active"),dColor=document.querySelector("#dark-colors .color-option.active");if(pColor)s.primaryColor=pColor.dataset.color;if(dColor)s.darkColor=dColor.dataset.color;s.logoUrl=document.getElementById("logo-url").value.trim();s.heroBg=document.getElementById("hero-bg").value.trim();DB.set("settings",s);toast("تم حفظ المظهر بنجاح")}
function exportData(){let data={categories:DB.get("categories",[]),menu:DB.get("menu",[]),offers:DB.get("offers",[]),settings:DB.get("settings",{}),password:DB.get("password","admin123")};let blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="alqaysar-backup-"+new Date().toISOString().slice(0,10)+".json";a.click();URL.revokeObjectURL(url);toast("تم تصدير البيانات")}
function importData(){let input=document.createElement("input");input.type="file";input.accept=".json";input.onchange=(e)=>{let file=e.target.files[0];if(!file)return;let reader=new FileReader();reader.onload=(ev)=>{try{let data=JSON.parse(ev.target.result);if(data.categories)DB.set("categories",data.categories);if(data.menu)DB.set("menu",data.menu);if(data.offers)DB.set("offers",data.offers);if(data.settings)DB.set("settings",data.settings);if(data.password)DB.set("password",data.password);toast("تم استيراد البيانات بنجاح");updateStats();renderMenuTable();renderCategoriesTable();renderOffersTable()}catch(err){toast("ملف غير صالح","error")}};reader.readAsText(file)};input.click()}
function resetData(){if(!confirm("هل أنت متأكد؟ سيتم حذف جميع البيانات!"))return;localStorage.removeItem("alqaysar_initialized");["categories","menu","offers","settings","password","visits"].forEach(k=>localStorage.removeItem("alqaysar_"+k));toast("تم إعادة التعيين");setTimeout(()=>location.reload(),1500)}
function initAdmin(){updateStats();renderMenuTable()}
document.addEventListener("DOMContentLoaded",checkAuth);
